/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

/**
 *
 * @author Reetoo
 */
public class ContentPane extends javax.swing.JPanel {
    int indexSelected = 0;
    CurrentWeatherPanel current;
    FutureWeatherPanel future;
    TravelPanel travel;

    /**
     * Creates new form VerticalLayoutPanel
     */
    public ContentPane() {
        System.out.println("1232323");
        initComponents();
        initalize();
        setOpaque(false);
        
    }
    public void initalize(){
        current = new CurrentWeatherPanel();
        //current.setBackground(Color.WHITE);
       // current.setOpaque(false);
        
        future = new FutureWeatherPanel();
     //   future.setBackground(Color.WHITE);
       // future.setOpaque(false);
        
        travel = new TravelPanel();
        add(current);
    }
    public void setPortrait(){
        future.setPortrait();
        travel.setPortrait();
    }
    public void setLandscape(){
        future.setLandscape();
        travel.setLandscape();
    }
    public void setCurrentWeatherPanel(){
        removeAll();
       // revalidate();
        add(current);
        revalidate();
        repaint();
    }
    public void setFutureWeatherPanel(){
        removeAll();
      //  revalidate();
        add(future);
        revalidate();
        repaint();
    }
    public void setTravelPanel(){
        removeAll();
       // revalidate();
        add(travel);
        revalidate();
        repaint();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 0));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
               
    }//GEN-LAST:event_formMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
   
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
