/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.handler.Util;
import weatherdata.WeatherCodeHandler;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author User
 */
public class DayWeatherBar extends javax.swing.JPanel {
    Font weatherFont;
    /**
     * Creates new form WeekBar
     */
    public DayWeatherBar() {
        initFont();
        initComponents();
    }
    public void setDayName(String s){
        dayName.setText(s);
    }
    public void setHighTemp(int n){
        highTemp.setText(n+"°C");
    }
    public void setLowTemp(int n){
        lowTemp.setText(n+"°C");
    }
    public void setWeather(int n){
        weatherIcon.setIcon(WeatherCodeHandler.getWeatherIcon(n));
    }
     public void setColour(Color color){
        setBackground(color);
    }
    
    private void initFont(){
        weatherFont = Util.getWeatherFont(25);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dayName = new javax.swing.JLabel();
        highTemp = new javax.swing.JLabel();
        lowTemp = new javax.swing.JLabel();
        weatherIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 0));
        setLayout(new java.awt.GridBagLayout());

        dayName.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        dayName.setForeground(new java.awt.Color(255, 255, 255));
        dayName.setText("Monday");
        dayName.setAlignmentX(1.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(dayName, gridBagConstraints);

        highTemp.setForeground(new java.awt.Color(255, 255, 255));
        highTemp.setText("0°");
        highTemp.setAlignmentX(1.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(highTemp, gridBagConstraints);

        lowTemp.setForeground(new java.awt.Color(255, 255, 255));
        lowTemp.setText("/0°");
        lowTemp.setAlignmentX(1.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        add(lowTemp, gridBagConstraints);

        weatherIcon.setFont(weatherFont);
        weatherIcon.setForeground(new java.awt.Color(255, 255, 255));
        weatherIcon.setText("T");
        weatherIcon.setAlignmentX(1.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        add(weatherIcon, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayName;
    private javax.swing.JLabel highTemp;
    private javax.swing.JLabel lowTemp;
    private javax.swing.JLabel weatherIcon;
    // End of variables declaration//GEN-END:variables
  

}
