/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

/**
 *
 * @author Reetoo
 */
public class FutureWeatherPanel extends javax.swing.JPanel {

    /**
     * Creates new form FutureWeatherPanel
     */
    public FutureWeatherPanel() {
        
        initComponents();
       setBackground(new Color(0,0,0,0));
      // jPanel1.setOpaque(false);
    }
    @Override
    public boolean isOpaque(){
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        weekWeather1 = new gui.WeekWeather();
        temperatureGraphPanel1 = new gui.TemperatureGraphPanel();
        currentWeatherPanel1 = new gui.CurrentWeatherPanel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 0.1;
        add(weekWeather1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        add(temperatureGraphPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(currentWeatherPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.CurrentWeatherPanel currentWeatherPanel1;
    private gui.TemperatureGraphPanel temperatureGraphPanel1;
    private gui.WeekWeather weekWeather1;
    // End of variables declaration//GEN-END:variables
}
