/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

/**
 *
 * @author Reetoo
 */
public class MainPanel extends javax.swing.JPanel {
    int indexSelected = 0;
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        this.setBackground(Color.BLACK);
    }
    public void swipeLeft(){
           
        indexSelected--;
        if(indexSelected<0){
            indexSelected = 2;
        }
        if(indexSelected==0){
            verticalLayoutPanel1.setCurrentWeatherPanel();
        }
        if(indexSelected==1){
            verticalLayoutPanel1.setFutureWeatherPanel();
        }
        if(indexSelected==2){
            verticalLayoutPanel1.setTravelPanel();
        }
    }
    public void swipeRight(){
        
        indexSelected++;
        if(indexSelected>2){
            indexSelected = 0;
        }
        if(indexSelected==0){
            verticalLayoutPanel1.setCurrentWeatherPanel();
        }
        if(indexSelected==1){
            verticalLayoutPanel1.setFutureWeatherPanel();
        }
        if(indexSelected==2){
            verticalLayoutPanel1.setTravelPanel();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        verticalLayoutPanel1 = new gui.VerticalLayoutPanel();
        topBar1 = new gui.TopBar();

        setLayout(new java.awt.GridBagLayout());

        verticalLayoutPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verticalLayoutPanel1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 353;
        gridBagConstraints.ipady = 455;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(verticalLayoutPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 374;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(topBar1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void verticalLayoutPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verticalLayoutPanel1MouseClicked
     
    }//GEN-LAST:event_verticalLayoutPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.TopBar topBar1;
    private gui.VerticalLayoutPanel verticalLayoutPanel1;
    // End of variables declaration//GEN-END:variables
}
