/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.handler.GUIHandler;
import java.util.ArrayList;

/**
 *
 * @author Reetoo
 */
public class TemperatureGraphPanel extends javax.swing.JPanel {
    TemperatureGraph temperatureGraph;
    /**
     * Creates new form TemperatureGraphPanel
     */
    public TemperatureGraphPanel() {
        initComponents();
        initGraph();
        initData();
        setOpaque(false);
    }
    public TemperatureGraph getGraph(){
        return temperatureGraph;
    }
    public void initGraph(){
        temperatureGraph = new TemperatureGraph();
        ArrayList<Integer> temps = new ArrayList<>();
        temps.add(0);
        temps.add(0);
        temps.add(0);
        temps.add(0);
        temps.add(0);
        temps.add(0);
        temps.add(0);
        temps.add(0);
        temperatureGraph.setGraph(temps);
        add(temperatureGraph);
    }
    public void initData(){
        ArrayList<Integer> data = GUIHandler.getTodayTemperatures();
        temperatureGraph.setGraph(data);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(1, 0));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
