/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Reetoo
 */
public class TemperatureGraphPanel extends javax.swing.JPanel {

    /**
     * Creates new form TemperatureGraphPanel
     */
    public TemperatureGraphPanel() {
        initComponents();
    }
    public TemperatureGraph getGraph(){
        return temperatureGraph1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temperatureGraph1 = new gui.TemperatureGraph();

        setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout temperatureGraph1Layout = new javax.swing.GroupLayout(temperatureGraph1);
        temperatureGraph1.setLayout(temperatureGraph1Layout);
        temperatureGraph1Layout.setHorizontalGroup(
            temperatureGraph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        temperatureGraph1Layout.setVerticalGroup(
            temperatureGraph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(temperatureGraph1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.TemperatureGraph temperatureGraph1;
    // End of variables declaration//GEN-END:variables
}
