/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.handler.GUIHandler;
import gui.handler.Util;
import java.awt.GridBagConstraints;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Reetoo
 */
public class WeekWeather extends javax.swing.JPanel {
    ArrayList<DayWeatherBar> components;
    DayWeatherBar bar1, bar2, bar3, bar4, bar5;
    /**
     * Creates new form WeekWeather
     */
    public WeekWeather() {
        components = new ArrayList<>();
        initBars();
        initComponents();
        initiate();
        initWeatherData();
        setOpaque(false);
        
    }
    public void initWeatherData(){
        String[] nextDays = Util.getNextDays(4);
        for(int i=0; i<components.size(); i++){
            components.get(i).setDayName(nextDays[i]);
        }
        getData();
    }
    public void initiate(){
       
        
         GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.BOTH;
        c.weightx = 0.1;
        c.weighty = 0.1;
        
        add(bar1,c);
        
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 1;
        c.fill = GridBagConstraints.BOTH;
        c.weightx = 0.1;
        c.weighty = 0.1;
        add(bar2,c);
        
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 2;
        c.fill = GridBagConstraints.BOTH;
        c.weightx = 0.1;
        c.weighty = 0.1;
        add(bar3,c);
        
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 3;
        c.fill = GridBagConstraints.BOTH;
        c.weightx = 0.1;
        c.weighty = 0.1;
        add(bar4,c);
        
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 4;
        c.fill = GridBagConstraints.BOTH;
        c.weightx = 0.1;
        c.weighty = 0.1;
        //add(bar5,c);
        
    }
    public void getData(){
        ArrayList<ArrayList<String>> data = GUIHandler.getFourDaysWeather();
        for(int i=0; i<data.size(); i++){
            components.get(i).setWeather(data.get(i).get(0));
            components.get(i).setHighTemp(data.get(i).get(1));
            components.get(i).setLowTemp(data.get(i).get(2));
        }
    }
    public void initBars(){
        bar1 = new DayWeatherBar();
        bar2 = new DayWeatherBar();
        bar3 = new DayWeatherBar();
        bar4 = new DayWeatherBar();
        bar5 = new DayWeatherBar();
        components.clear();
        components.add(bar1);
        components.add(bar2);
        components.add(bar3);
        components.add(bar4);
        //components.add(bar5);
        
    }
    public void initDayNames(){
        String[] dayNames = Util.getNextDays(100);
        bar1.setDayName(dayNames[0]);
        bar2.setDayName(dayNames[1]);
        bar3.setDayName(dayNames[2]);
        bar4.setDayName(dayNames[3]);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
