/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.handler.Util;
import java.util.ArrayList;

/**
 *
 * @author Reetoo
 */
public class WeekWeather extends javax.swing.JPanel {
    ArrayList<DayWeatherBar> components;
    DayWeatherBar bar1, bar2, bar3, bar4, bar5;
    /**
     * Creates new form WeekWeather
     */
    public WeekWeather() {
        components = new ArrayList<>();
        initBars();
        initComponents();
        initiate();
    }
    public void initWeatherData(){
        String[] nextDays = Util.getNextDays(4);
        for(int i=0; i<components.size(); i++){
            components.get(i).setDayName(nextDays[i]);
        }
    }
    public void initiate(){
        add(bar1);
        add(bar2);
        add(bar3);
        add(bar4);
        add(bar5);
        
    }
    public void initBars(){
        bar1 = new DayWeatherBar();
        bar2 = new DayWeatherBar();
        bar3 = new DayWeatherBar();
        bar4 = new DayWeatherBar();
        bar5 = new DayWeatherBar();
        components.clear();
        components.add(bar1);
        components.add(bar2);
        components.add(bar3);
        components.add(bar4);
        components.add(bar5);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
