/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.handler.Util;
import weatherdata.WeatherCodeHandler;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author User
 */
public class DayWeatherBar extends javax.swing.JPanel {
    //Font weatherFont;
    /**
     * Creates new form WeekBar
     */
    public DayWeatherBar() {
        //initFont();
        initComponents();
        initalize();
        jPanel1.setOpaque(false);
        setOpaque(false);
    }
    public void initalize(){
        weatherIcon.setFont(Util.getWeatherFont(25));
    }
    public void setDayName(String s){
        dayName.setText(s);
    }
    public void setHighTemp(String n){
        highTemp.setText(n+"°");
    }
    public void setLowTemp(String n){
        lowTemp.setText(n+"°");
    }
    public void setWeather(String s){
        weatherIcon.setText(s);
    }
     public void setColour(Color color){
        setBackground(color);
    }
    
   //private void initFont(){
    //   weatherFont = Util.getWeatherFont(25);
   // }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dayName = new javax.swing.JLabel();
        weatherIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        highTemp = new javax.swing.JLabel();
        lowTemp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 0));
        setLayout(new java.awt.GridBagLayout());

        dayName.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        dayName.setForeground(new java.awt.Color(255, 255, 255));
        dayName.setText("Monday");
        dayName.setAlignmentX(1.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(dayName, gridBagConstraints);

        weatherIcon.setForeground(new java.awt.Color(255, 255, 255));
        weatherIcon.setText("T");
        weatherIcon.setAlignmentX(1.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 1.0;
        add(weatherIcon, gridBagConstraints);

        highTemp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        highTemp.setForeground(new java.awt.Color(255, 255, 255));
        highTemp.setText("0");
        highTemp.setAlignmentX(1.0F);
        jPanel1.add(highTemp);

        lowTemp.setForeground(new java.awt.Color(204, 204, 204));
        lowTemp.setText("0");
        lowTemp.setAlignmentX(1.0F);
        jPanel1.add(lowTemp);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayName;
    private javax.swing.JLabel highTemp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lowTemp;
    private javax.swing.JLabel weatherIcon;
    // End of variables declaration//GEN-END:variables
  

}
