/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;

/**
 *
 * @author Reetoo
 */
public class FutureWeatherPanel extends javax.swing.JPanel {

    /**
     * Creates new form FutureWeatherPanel
     */
    public FutureWeatherPanel() {
        
        initComponents();
        currentWeatherPanel1.dimBackground();
       setBackground(new Color(0,0,0,0));

      // jPanel1.setOpaque(false);
    }
    @Override
    public boolean isOpaque(){
        return true;
    }
    public void setLandscape(){
        System.out.println("Hello");
        currentWeatherPanel1.setTempSize(100);
        removeAll();
        GridBagConstraints  c = new GridBagConstraints();

        c.fill = GridBagConstraints.BOTH;
        add(currentWeatherPanel1,c);
        
        c = new GridBagConstraints();
        c.gridx = 1;
        c.gridy = 0;
                c.weightx = 1;
        c.weighty = 1;
        c.fill = GridBagConstraints.BOTH;
        c.anchor = GridBagConstraints.LAST_LINE_START;
        temperatureGraphPanel1.resizeGraph(new Dimension(345,130));
        add(temperatureGraphPanel1,c);
        
        c = new GridBagConstraints();
         c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 2;
        c.fill = GridBagConstraints.BOTH;
        
        add(weekWeather1,c);
        
        
        revalidate();
        repaint();
       
    }
    public void setPortrait(){
        removeAll();
        currentWeatherPanel1.setTempSize(120);
        GridBagConstraints  c = new GridBagConstraints();
         c = new java.awt.GridBagConstraints();
        c.anchor = GridBagConstraints.LAST_LINE_START;
        c.fill = GridBagConstraints.BOTH;
        
        c.weightx = 1.0;
        c.weighty = 1.0;
        add(currentWeatherPanel1,c);
        
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 1;
        c.fill = GridBagConstraints.BOTH;
        c.ipady = 100;
        c.anchor = GridBagConstraints.PAGE_END;
        temperatureGraphPanel1.resizeGraph(new Dimension(320,100));
        add(temperatureGraphPanel1,c);
         
         
        c = new GridBagConstraints();
       c.gridx = 0;
        c.gridy = 2;
        c.fill = GridBagConstraints.HORIZONTAL;
        c.anchor = GridBagConstraints.PAGE_END;
        c.weightx = 0.1;

        add(weekWeather1,c);
        

        revalidate();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        weekWeather1 = new gui.WeekWeather();
        temperatureGraphPanel1 = new gui.TemperatureGraphPanel();
        currentWeatherPanel1 = new gui.CurrentWeatherPanel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 0.1;
        add(weekWeather1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        add(temperatureGraphPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(currentWeatherPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.CurrentWeatherPanel currentWeatherPanel1;
    private gui.TemperatureGraphPanel temperatureGraphPanel1;
    private gui.WeekWeather weekWeather1;
    // End of variables declaration//GEN-END:variables


}
