/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

/**
 *
 * @author User
 */
public class HorizontalLayoutPanel extends javax.swing.JPanel {

    /**
     * Creates new form HorizontalLayoutPanel
     */
    public HorizontalLayoutPanel() {
        initComponents();
    }
    public void setColour(Color c){
       // currentWeatherPanel1.setColour(c);
        //thisWeekWeatherPanel1.setColour(c);
       // weatherPanel1.setColour(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        trainStatusPanel1 = new gui.TrainStatusPanel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(trainStatusPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.TrainStatusPanel trainStatusPanel1;
    // End of variables declaration//GEN-END:variables
}
