/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;

/**
 *
 * @author User
 */
public class HorizontalLayoutPanel extends javax.swing.JPanel {

    /**
     * Creates new form HorizontalLayoutPanel
     */
    public HorizontalLayoutPanel() {
        initComponents();
    }
    public void setColour(Color c){
        currentWeatherPanel1.setColour(c);
        thisWeekWeatherPanel1.setColour(c);
        weatherPanel1.setColour(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        currentWeatherPanel1 = new Main.CurrentWeatherPanel();
        thisWeekWeatherPanel1 = new Main.ThisWeekWeatherPanel();
        trainStatusPanel1 = new Main.TrainStatusPanel();
        weatherPanel1 = new Main.WeatherPanel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(currentWeatherPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(thisWeekWeatherPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(trainStatusPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(weatherPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Main.CurrentWeatherPanel currentWeatherPanel1;
    private Main.ThisWeekWeatherPanel thisWeekWeatherPanel1;
    private Main.TrainStatusPanel trainStatusPanel1;
    private Main.WeatherPanel weatherPanel1;
    // End of variables declaration//GEN-END:variables
}
