package Main;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class ThisWeekWeatherPanel extends javax.swing.JPanel {
    
    ArrayList<DayWeatherBar> components;
    /**
     * Creates new form DayWeatherPanel
     */
    public ThisWeekWeatherPanel() {
        components = new ArrayList<>();
        initComponents();
        initWeatherData();
    }
    public void initDays(){

    }
     public void setColour(Color color){
         for(DayWeatherBar dwb: components){
            dwb.setBackground(color);
         }
    }
    public void initWeatherData(){
        String[] nextDays = Util.getNextDays(4);
        for(int i=0; i<components.size(); i++){
            components.get(i).setDayName(nextDays[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        weekBar2 = new Main.DayWeatherBar();
        weekBar3 = new Main.DayWeatherBar();
        weekBar4 = new Main.DayWeatherBar();
        weekBar6 = new Main.DayWeatherBar();

        setLayout(new java.awt.GridBagLayout());

        weekBar2.setDayName("Tommorow");
        components.add(weekBar2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(weekBar2, gridBagConstraints);

        weekBar3.setDayName("Wed");
        components.add(weekBar3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(weekBar3, gridBagConstraints);

        weekBar4.setDayName("Thu");
        components.add(weekBar4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(weekBar4, gridBagConstraints);

        weekBar6.setDayName("Fri");
        components.add(weekBar6);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(weekBar6, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Main.DayWeatherBar weekBar2;
    private Main.DayWeatherBar weekBar3;
    private Main.DayWeatherBar weekBar4;
    private Main.DayWeatherBar weekBar6;
    // End of variables declaration//GEN-END:variables
}
