/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;

/**
 *
 * @author User
 */
public class VerticalLayoutPanel extends javax.swing.JPanel {

    /**
     * Creates new form VerticalLayoutPanel
     */
    public VerticalLayoutPanel() {
        initComponents();
    }
        public void setColour(Color c){
        currentWeatherPanel1.setColour(c);
       // thisWeekWeatherPanel1.setColour(c);
        //weatherPanel1.setColour(c);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        trainStatusPanel1 = new Main.TrainStatusPanel();
        currentWeatherPanel1 = new Main.CurrentWeatherPanel();
        temperatureBar2 = new Main.TemperatureBar();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(currentWeatherPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(temperatureBar2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Main.CurrentWeatherPanel currentWeatherPanel1;
    private Main.TemperatureBar temperatureBar2;
    private Main.TrainStatusPanel trainStatusPanel1;
    // End of variables declaration//GEN-END:variables
}
